{
	"name": "admin-template",
	"author": "unevenll@yeah.net",
	"private": true,
	"version": "DNK_S_DOP_MP_V1.0.1.2_20230320",
	"keywords": [
		"vue",
		"vite",
		"eslint",
		"typescript",
		"husky",
		"volta"
	],
	"scripts": {
		"dev": "vite",
		"build": "vue-tsc --noEmit && vite build",
		"preview": "vite preview",
		"eslint:comment": "使用 ESLint 检查并自动修复 src 目录下所有扩展名为 .js 和 .vue 的文件",
		"eslint": "eslint --ext .js,.vue --ignore-path .gitignore --fix src",
		"prettier:comment": "自动格式化当前目录下的所有文件",
		"prettier": "prettier --write",
		"commit:comment": "引导设置规范化的提交信息",
		"commit": "git-cz",
		"test": "vitest",
		"test:ui": "vitest --ui",
		"coverage": "vitest run --coverage",
		"gulp": "gulp -f scripts/gulpfile.ts",
		"ts-node": "ts-node ./scripts/gulpfile.ts"
	},
	"config": {
		"commitizen": {
			"path": "node_modules/cz-customizable"
		}
	},
	"lint-staged": {
		"*.{js,ts}": [
			"npm run eslint",
			"npm run prettier"
		]
	},
	"dependencies": {
		"@element-plus/icons-vue": "^2.3.1",
		"@types/gulp": "^4.0.10",
		"@types/qrcode": "^1.5.0",
		"@vitejs/plugin-legacy": "^4.0.1",
		"@vue-office/excel": "^0.2.4",
		"@vueuse/core": "^9.2.0",
		"archiver": "^5.3.1",
		"axios": "^0.27.2",
		"crypto-js": "^4.1.1",
		"docx-preview": "^0.1.15",
		"echarts": "^5.4.1",
		"element-plus": "^2.2.16",
		"gulp": "^4.0.2",
		"gulp-ssh": "^0.7.0",
		"html2canvas": "^1.4.1",
		"inquirer": "^9.1.4",
		"node-ssh": "^13.0.1",
		"nprogress": "^0.2.0",
		"ora": "^6.1.2",
		"path": "^0.12.7",
		"pinia": "^2.0.22",
		"pinia-plugin-persist": "^1.0.0",
		"qrcode": "^1.5.0",
		"readline-sync": "^1.4.10",
		"screenfull": "^6.0.2",
		"sucrase": "^3.29.0",
		"terser": "^5.16.1",
		"tslint": "^6.1.3",
		"unplugin-vue-setup-extend-plus": "^0.4.9",
		"vue": "^3.2.37",
		"vue-router": "^4.1.5"
	},
	"devDependencies": {
		"@babel/register": "^7.21.0",
		"@commitlint/cli": "^17.1.2",
		"@commitlint/config-conventional": "^17.1.0",
		"@types/archiver": "^5.3.2",
		"@types/crypto-js": "^4.1.1",
		"@types/node": "^18.15.1",
		"@types/nprogress": "^0.2.0",
		"@types/readline-sync": "^1.4.4",
		"@types/ssh2": "^1.11.7",
		"@typescript-eslint/eslint-plugin": "^5.36.2",
		"@typescript-eslint/parser": "^5.36.2",
		"@vitejs/plugin-vue": "^4.0.0",
		"@vitejs/plugin-vue-jsx": "^3.0.0",
		"@vitest/coverage-c8": "^0.28.4",
		"@vue/test-utils": "^2.0.0-rc.18",
		"c8": "^7.12.0",
		"commitizen": "^4.2.5",
		"commitlint-config-cz": "^0.13.3",
		"cz-conventional-changelog": "^3.3.0",
		"cz-customizable": "^7.0.0",
		"eslint": "^8.23.1",
		"eslint-config-prettier": "^8.5.0",
		"eslint-plugin-prettier": "^4.2.1",
		"eslint-plugin-vue": "^9.4.0",
		"gulp-autoprefixer": "^3.1.1",
		"gulp-cache": "^1.0.2",
		"gulp-clean-css": "^3.10.0",
		"gulp-htmlclean": "^2.7.15",
		"gulp-htmlmin": "^3.0.0",
		"gulp-if": "^2.0.2",
		"gulp-imagemin": "^4.1.0",
		"gulp-minify-css": "^1.2.4",
		"gulp-notify": "^3.0.0",
		"gulp-path": "^3.0.3",
		"gulp-rev-append": "^0.1.8",
		"gulp-sequence": "^0.4.6",
		"gulp-sourcemaps": "^2.6.4",
		"gulp-uglify": "^2.0.0",
		"happy-dom": "^8.2.6",
		"husky": "7.0.4",
		"identity-obj-proxy": "^3.0.0",
		"js-md5": "^0.7.3",
		"jsdom": "^21.1.0",
		"less": "^4.1.3",
		"lint-staged": "^13.0.3",
		"prettier": "^2.7.1",
		"sass": "^1.54.9",
		"ssh2": "^1.11.0",
		"tslib": "^2.5.0",
		"typescript": "^4.6.4",
		"uglify-js": "^3.3.9",
		"unocss": "^0.58.6",
		"unplugin-auto-import": "^0.11.2",
		"unplugin-element-plus": "^0.4.1",
		"unplugin-vue-components": "^0.22.7",
		"vite": "^4.1.0",
		"vite-plugin-compression": "^0.5.1",
		"vite-plugin-style-import": "^2.0.0",
		"vite-plugin-vue-setup-extend-plus": "^0.1.0",
		"vitest": "^0.28.3",
		"vue-i18n": "^9.10.1",
		"vue-tsc": "^0.40.4"
	},
	"volta": {
		"node": "18.15.0",
		"yarn": "1.22.19"
	}
}
