export const adminConfigData: RoleInfo = {
    id: 1,
    roleName: '管理员',
    roleCode: '1',
    isEnable: '1',
    remark: '管理员的角色',
    menuIdList: [],
    menuList: [
        {
            id: 169,
            menuName: '控制台',
            menuUrl: '/main',
            parentId: 0,
            menuLever: 0,
            menuType: '1',
            menuIcon: 'DataBoard',
            isEnable: '1',
            sort: 1,
            remark: '',
        },
        {
            id: 120,
            menuName: '系统管理',
            menuUrl: '/system',
            parentId: 0,
            menuLever: 0,
            menuType: '1',
            menuIcon: 'Setting',
            isEnable: '1',
            sort: 5,
            remark: '',
        },
        {
            id: 121,
            menuName: '菜单管理',
            menuUrl: '/system/menuManage',
            parentId: 120,
            menuLever: 0,
            menuType: '2',
            menuIcon: '',
            isEnable: '1',
            sort: 1,
            remark: '',
        },
    ],
};
