export enum authBtnEnum {
    BACK = '返回',
    SEARCH = '搜索',
    RESET = '重置',
    DETAIL = '详情',
    ADD = '新增',
    MODIFY = '修改',
    DELETE = '删除',
    MULTI_DELETE = '批量删除',
    CONNECT_TEST = '测试连接',
    MISSION_OPEN = '开启任务',
    MISSION_END = '结束任务',
    PARAMS_MATCH = '字段匹配',
    ADD_USER = '添加用户',
    INVOKE_RECORD = '调用记录',
    READ_LOG = '读取日志',
    MENU_AUTH = '菜单权限',
    OPERATE_AUTH = '操作权限',
    ADD_NEW_DICT_TYPE = '新增字典类型',
    ADD_NEW_DICT_VAL = '新增字典值',
    DICT_VALUE = '字典值',
    BACK_UP = '备份',
    RECOVER = '一键还原',
    IMPORT = '导入',
    EXPORT = '导出',
    REFRESH = '刷新设备',
    REBOOT = '重启',
    SHUTDOWN = '关机',
    MULTI_SETTING = '批量设置开关机',
    LIVE_PICTURE = '实时画面',
    BUSINESS_PLATFORM = '业务平台',
}
export enum authTabEnum {
    SEARCH_DATA_BASE = '查询数据库',
    WEB_SERVICE_REQ = 'WebService(主动请求)',
    WEB_SERVICE_ACCEPT = 'WebService(第三方推送)',
    HTTP_REQ = 'HTTP(主动请求)',
}
